apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: mazenturky/order-processing-service:latest
        ports:
        - containerPort: 8002
