apiVersion: v1
kind: Service
metadata:
  name: user-login-signup-service  # Updated to use valid DNS-1035 label
spec:
  selector:
    app: user-login-signup
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
